#pragma once

#include <filesystem>
#include <fstream>
#include <string>
#include <toml++/toml.hpp>

void generate_include_file ( const toml::table &local_config,
                             const toml::table &global_config,
                             std::string &includes,
                             Flags_t &flags ) {
  fs::create_directories ( "target/crb_inc" ); // clarbe includes

  includes += " -I target/crb_inc ";
  std::ofstream include_file ( "target/crb_inc/config_param.h", std::fstream::trunc );
  include_file << "///* File generated by clarbe, do not edit. *///\n"
               << "#ifndef CLARBE_GEN_INCLUDE_FILE\n"
               << "#define CLARBE_GEN_INCLUDE_FILE\n"
               << "#define CLARBE_FLAG_CMD_WINDOW " << flags.cmd_window << '\n'
               << "#define CLARBE_FLAG_DEBUG " << flags.debug << '\n'
               << "#define CLARBE_FLAG_RELEASE " << flags.release << '\n'
               << "#define CLARBE_FLAG_OPTIMIZATION " << flags.optimization << '\n';

  if ( local_config[ "package" ][ "version" ] ) {
    include_file << "#define CLARBE_LOCAL_SOFTWARE_VERSION \""
                 << *( local_config[ "package" ][ "version" ].value< std::string > () ) << "\"\n";
  }
  if ( local_config[ "package" ][ "name" ] ) {
    include_file << "#define CLARBE_PACKAGE_NAME \""
                 << *( local_config[ "package" ][ "name" ].value< std::string > () ) << "\"\n";
  }
  if ( local_config[ "package" ][ "build_type" ] ) {
    include_file << "#define CLARBE_PACKAGE_TYPE \""
                 << *( local_config[ "package" ][ "build_type" ].value< std::string > () ) << "\"\n";
  }

  include_file << "#endif";
  include_file.flush ();
  include_file.close ();
}
